FROM ubuntu:14.04
MAINTAINER Hook <hook@decepticons.tr>

ENV http_proxy http://proxy.unlu.edu.ar:8080
ENV https_proxy http://proxy.unlu.edu.ar:8080

RUN apt-get update && apt-get -y install apache2 && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

RUN /usr/sbin/a2ensite default-ssl
RUN /usr/sbin/a2enmod ssl

EXPOSE 80
EXPOSE 443

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

